import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./styled-component/registry";
import { GlobalStyle } from "./styled-component/global";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "./services/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "R-Query",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <StyledComponentsRegistry>
            {children}
            <GlobalStyle />
          </StyledComponentsRegistry>
        </QueryClientProvider>
      </body>
    </html>
  );
}
